apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-board
  labels:
    app: collab-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collab-board
  template:
    metadata:
      labels:
        app: collab-board
    spec:
      containers:
      - name: collab-board
        image: collab-board:latest
        imagePullPolicy: Never # Force local image built in Rancher Desktop
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://db:27017/collab-board
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: collab-board-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
  selector:
    app: collab-board
